# example config for CuNeRF

# training
max_iter : 200000
eval_iter: 10000
save_iter: $eval_iter
log_iter : 100
bs_train : 1024 # batch size 
bs_eval  : 32768
bs_test  : $bs_eval
N_eval   : 
lr       : 0.002
lr_final : 0.00002
workers  : 4

# modeling
stype     : cube
radius    : 1
n_samples : 64 #64
n_imps    : 64 #64
mtype     : NGPMLP
hierachical: False

# test
zpos      : [0]
scales    : [1]
angles    : [0]
asteps    : 45
axis      : [0, 1, 1]
cam_scale : 1.5

# path
result_path : save
save_path   : save
log_path    : save

loss : 
  name : MSE_LOSS

sampling : 
  stype     : $stype
  n_samples : $n_samples

rendering :
  stype : $stype

importance :
  stype     : $stype
  n_samples : $n_imps

model : 
  name    : $mtype
  netD    : 8
  netW    : 256
  in_ch   : 3
  out_ch  : 2
  skips   : [4]
  hash_encoding_parameters:
    otype: HashGrid
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 19
    base_resolution: 16
    per_level_scale: 2.0

model_ft : 

dataset : 
  mode : $mode
  dname: Medical3D
  train : 
    file    : $file
    scale   : $scale
    radius  : $radius
    bsize   : $bs_train
    modality: $modality 

  eval :
    file    : $file
    scale   : $scale
    radius  : $radius
    N_eval  : $N_eval
    bsize   : $bs_eval
    modality: $modality 

  test :
    file      : $file
    scales    : $scales
    radius    : $radius
    axis      : $axis
    angles    : $angles
    zpos      : $zpos
    cam_scale : $cam_scale
    asteps    : $asteps

dataloader :
  mode : $mode
  train :
    batch_size : 1
    shuffle : True
  
  eval:
    batch_size : 1
    shuffle : False

  test:
    batch_size : 1
    shuffle : False

optim :
  name : Adam
  lr   : $lr
  betas: [0.9, 0.999]
  eps  : 0.000001

metrics : 
  psnr  : True
  ssim  : True
  lpips : False
  avg   : False

lr_decay : 
  lr_init        : $lr
  lr_final       : $lr_final
  max_iter       : $max_iter
  lr_delay_steps : 1000
  lr_delay_mult  : 0.01

clip_grad :
  max_val  : 0.1
  max_norm : 0.1